### ISSUE TITLE
Can a basic authentication be added to the webserver? Or option to disable it alltogether 

### ISSUE THREAD

**Issue by skynet01** [ratgdo/esphome-ratgdo#105]
Since Ratgdo controls the garage and all ..
.. any chance you can add a user/pass authentication option? It's already built-in into the ESP-Home webserver: https://esphome.io/components/web_server.html just needs to be enabled.

having an option to disable the web server altogether would be great as well :)

**Comment by rlowens** [comment]
You can just adopt the ratgdo into your local ESPHome Addon and edit the device .yaml to do that yourself.

**Comment by skynet01** [comment]
... yes but then if there are any updates I won't get them automatically. 
 Thought it would be a good feature to have to request it here since anyone connected to your network will be able to open your garage door.

**Comment by rlowens** [comment]
> ... yes but then if there are any updates I won't get them automatically.

No, only changes to the included packages are updated. Your local device .yaml is never updated, so you can add the changes there.

```
web_server:
  auth:
    username: !secret web_username
    password: !secret web_password

```

> Thought it would be a good feature to have to request it here since anyone connected to your network will be able to open your garage door.

Fair point.

**Comment by skynet01** [comment]
nice, I didn't know I could declare my own parameters if you already declared "web_server" in your yaml. Thanks, for the tip

**Comment by mdjhnson** [comment]
I'm not running Home Assistant so I've got a container of ESPHome running. I'm able to add my ratgdo and edit the yaml. However, I keep breaking it somehow. It fails to connect to the network and boot. 

Here's the yaml I'm trying to install. Can anyone help me figure out what I'm doing wrong?

```
substitutions:
  name: ratgdov25i-30f6e3
  friendly_name: ratgdov2.5i 30f6e3
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: WGf4TkAe6ANgN2wiCvM5yAPlt8UX164jCr1WbxGjOYw=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

web_server:
  auth:
    username: complexusernamehere
    password: complexpasswordhere
```
