### ISSUE TITLE
Heads up: ESPHome firmware does not support Security 1.0 openers (purple learn button)

### ISSUE THREAD

**Issue by avwuff** [ratgdo/esphome-ratgdo#128]
I just spent an hour trying to get this to work and had no success.  Turns out it's not supported in ESPHome firmware.

https://paulwieland.github.io/ratgdo/01_features.html

Just letting others know so they don't waste their time.

**Comment by niemyjski** [comment]
This is a duplicate of https://github.com/ratgdo/esphome-ratgdo/issues/70#issuecomment-1813189602 and it's marked as coming soon in the readme. An update by @PaulWieland would be greatly appreciated.

**Comment by Kylar514** [comment]
Interesting, just out of curioustiy what where the symptoms you were facing?  

I have a brown button, which according to Chamberlain is the same as a purple, so it seems I an on Security 1.0.  The weird thing is, I was able to get it to work intermittently.  I have full status on obstruction sensors, toggling the door open and closed will work few and far between, mostly I am just getting a issue that says 
`17:12:06	[W]	[component:214]	

Component preferences took a long time for an operation (0.05 s).

17:12:06	[W]	[component:215]	

Components should block for at most 20-30ms.`

I assume thats what you were getting as well.

**Comment by bdraco** [comment]
duplicate of https://github.com/ratgdo/esphome-ratgdo/issues/62

**Comment by miles267** [comment]
Coming soon as in approx when? (ESPHome Security 1.0)

**Comment by mariusmuja** [comment]
It has been implemented, but it is completely untested as of now.

People feeling brave are welcome to try this branch: https://github.com/ratgdo/esphome-ratgdo/tree/sec_plus_v1, but be aware it's likely to have bugs. If so, posting the logs here could help fix those bugs...

**Comment by miles267** [comment]
@mariusmuja are testers needed to progress this? It seems the user community is anxiously watching the production release page for ESPHome with Security 1.0 support and most or all users did not see your post here w a pre-release version.

**Comment by mariusmuja** [comment]
@miles267 Yes, more testers would be nice. It's only been implemented for a few of days now, and I have no way to directly test it, relying 100% on other people to report issues with it and post debug logs.

**Comment by miles267** [comment]
@mariusmuja are you able to update this page to include a link so more users are aware and can find this info? https://ratgdo.github.io/esphome-ratgdo/

**Comment by 4rsfed** [comment]
Can someone link me to what's necessary to flash this untested code? i am not familiar with ESP devices, but have 3 2.5 boards waiting for Sec1 support so happy to flash them and report issues/logs. 
Just not sure how to flash them/update them.

**Comment by smarthomeaf** [comment]
I am trying to use the branch code, but i am having issues compiling.   `Would` someone be able to point me in the right direction.   I am willing to do any testing that is required. 

Here is what i am getting during validation

<img width="621" alt="image" src="https://github.com/ratgdo/esphome-ratgdo/assets/105226208/ff0f1292-fb04-40f4-9556-cc5ec935d4dc">


Here is my code block 


```
substitutions:
  name: "garage-door-right"
  friendly_name: Garage Door Right
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@sec_plus_v1
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: I0Vo0DyYe9xsJny5JPGhw85Lc9942fPI34qlqnfgz1E=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password


external_components:
  - source:
      type: git
      url: https://github.com/ratgdo/esphome-ratgdo
      ref: sec_plus_v1
    refresh: 1s

preferences:
  flash_write_interval: 5s

ratgdo:
  id: ${id_prefix}
  input_gdo_pin: ${uart_rx_pin}
  output_gdo_pin: ${uart_tx_pin}
  input_obst_pin: ${input_obst_pin}
  protocol: secplusv1
  on_sync_failed:
    then:
      - homeassistant.service:
          service: persistent_notification.create
          data:
            title: "${friendly_name} sync failed"
            message: "Failed to communicate with garage opener on startup."
            notification_id: "esphome_ratgdo_${id_prefix}_sync_failed"

lock:
  - platform: ratgdo
    id: ${id_prefix}_lock_remotes
    ratgdo_id: ${id_prefix}
    name: "Lock remotes"

switch:
  - platform: gpio
    id: "${id_prefix}_status_door"
    internal: true
    pin:
      number: ${status_door_pin}  # D0 output door status, HIGH for open, LOW for closed
      mode:
        output: true
    name: "Status door"
    entity_category: diagnostic
  - platform: gpio
    id: "${id_prefix}_status_obstruction"
    internal: true
    pin:
      number: ${status_obstruction_pin}  # D8 output for obstruction status, HIGH for obstructed, LOW for clear
      mode:
        output: true
    name: "Status obstruction"
    entity_category: diagnostic

binary_sensor:
  - platform: ratgdo
    type: motion
    id: ${id_prefix}_motion
    ratgdo_id: ${id_prefix}
    name: "Motion"
    device_class: motion
  - platform: ratgdo
    type: obstruction
    id: ${id_prefix}_obstruction
    ratgdo_id: ${id_prefix}
    name: "Obstruction"
    device_class: problem
    on_press:
      - switch.turn_on: ${id_prefix}_status_obstruction
    on_release:
      - switch.turn_off: ${id_prefix}_status_obstruction
  - platform: ratgdo
    type: button
    id: ${id_prefix}_button
    ratgdo_id: ${id_prefix}
    name: "Button"
    entity_category: diagnostic
  - platform: gpio
    id: "${id_prefix}_dry_contact_open"
    pin:
      number: ${dry_contact_open_pin}  # D5 dry contact for opening door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact open"
    entity_category: diagnostic
    filters:
      - delayed_on_off: 500ms
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${id_prefix}_dry_contact_close
          then:
            - cover.open: ${id_prefix}_garage_door
  - platform: gpio
    id: "${id_prefix}_dry_contact_close"
    pin:
      number: ${dry_contact_close_pin}  # D6 dry contact for closing door
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact close"
    entity_category: diagnostic
    filters:
      - delayed_on_off: 500ms
    on_press:
      - if:
          condition:
            binary_sensor.is_off: ${id_prefix}_dry_contact_open
          then:
            - cover.close: ${id_prefix}_garage_door
  - platform: gpio
    id: "${id_prefix}_dry_contact_light"
    pin:
      number: ${dry_contact_light_pin}  # D3 dry contact for triggering light (no discrete light commands, so toggle only)
      inverted: true
      mode:
        input: true
        pullup: true
    name: "Dry contact light"
    entity_category: diagnostic
    filters:
      - delayed_on_off: 500ms
    on_press:
      - light.toggle: ${id_prefix}_light

number:
  - platform: ratgdo
    id: ${id_prefix}_rolling_code_counter
    type: rolling_code_counter
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Rolling code counter"
    mode: box
    unit_of_measurement: "codes"

  - platform: ratgdo
    id: ${id_prefix}_opening_duration
    type: opening_duration
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Opening duration"
    unit_of_measurement: "s"

  - platform: ratgdo
    id: ${id_prefix}_closing_duration
    type: closing_duration
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Closing duration"
    unit_of_measurement: "s"

  - platform: ratgdo
    id: ${id_prefix}_client_id
    type: client_id
    entity_category: config
    ratgdo_id: ${id_prefix}
    name: "Client ID"
    mode: box

cover:
  - platform: ratgdo
    id: ${id_prefix}_garage_door
    device_class: garage
    name: "Door"
    ratgdo_id: ${id_prefix}
    on_closed:
      - switch.turn_off: ${id_prefix}_status_door
    on_open:
      - switch.turn_on: ${id_prefix}_status_door

light:
  - platform: ratgdo
    id: ${id_prefix}_light
    name: "Light"
    ratgdo_id: ${id_prefix}

button:
  - platform: restart
    name: "Restart"
  - platform: safe_mode
    name: "Safe mode boot"
    entity_category: diagnostic

  - platform: template
    id: ${id_prefix}_query_status
    entity_category: diagnostic
    name: "Query status"
    on_press:
      then:
        lambda: !lambda |-
          id($id_prefix).query_status();

  - platform: template
    id: ${id_prefix}_sync
    name: "Sync"
    entity_category: diagnostic
    on_press:
      then:
        lambda: !lambda |-
          id($id_prefix).sync();

  - platform: template
    id: ${id_prefix}_toggle_door
    name: "Toggle door"
    on_press:
      then:
        lambda: !lambda |-
          id($id_prefix).door_toggle();

```

**Comment by PaulWieland** [comment]
With [esphome cli](https://esphome.io/guides/getting_started_command_line.html) installed:

* Save the [yaml file](https://raw.githubusercontent.com/ratgdo/esphome-ratgdo/sec_plus_v1/static/v25iboard_secplusv1.yaml) to your computer 
* Edit the file and set your wifi credentials under the "wifi" section as follows:
  *  delete `ap`
  * add `ssid: YOUR_SSID`
  * add `password: YOUR_PASSWORD`
  * save
 * run `esphome run v25iboard_secplusv1.yaml` to compile and install

**Comment by 4rsfed** [comment]
Hooked up to my purple button  SEC1.0 and the light control works (on/off) the garage goes up, but will not go down. 
Is there a way to get the logs out of the ESP UI to paste them here? I see the live log on the webUI, but I can't go back to the time I tested.

**Comment by rlowens** [comment]
> Is there a way to get the logs out of the ESP UI to paste them here?

If you have ESPHome CLI, you can run `esphome log v25iboard_secplusv1.yaml`

If you have ESPHome Addon, click LOGS on the device in ESPHome UI.

Can also view the device's webpage/evenst, like http://ratgdo1.local/events or http://192.168.1.172/events

**Comment by 4rsfed** [comment]
Log file attached here 
[sec1.log](https://github.com/ratgdo/esphome-ratgdo/files/13956658/sec1.log)

**Comment by mariusmuja** [comment]
> Log file attached here

I can't find any door interaction in this log. Can you capture another log where you open/close the door? and update to the latest, I added a bit of extra logging.

**Comment by 4rsfed** [comment]
[sec1 second try.log](https://github.com/ratgdo/esphome-ratgdo/files/13959124/sec1.second.try.log)

Working now (up, down, and lights) 
I had the wiring for the obstruction sensor incorrect the first time.

**Comment by miles267** [comment]
@4rsfed is ESPHome also allowing you to calibrate the door open and close as well as place the door partial open position with Security 1.0? I saw this was a feature of Security 2.0.

**Comment by 4rsfed** [comment]
Looking at the second log file I posted, doesn't have the positions......
not sure if I am doing something wrong when going to ip/events but I see the updates on the UI (took a video recording of the screen as it was going up and down)
<img width="761" alt="image" src="https://github.com/ratgdo/esphome-ratgdo/assets/8016700/1dd8072e-825e-428d-9faa-e05aed0c3382">

**Comment by PaulWieland** [comment]
@4rsfed what color is your learn button?

**Comment by miles267** [comment]
Looks like this could be nearing production? Appreciate the testing. We’ve had unseasonably cold temps making it difficult to spend time in garage.

**Comment by smarthomeaf** [comment]
Works great other than not knowing if the door is open or closed.   V1 has no way of knowing if door is open or closed.  I can work around this by creating a custom cover using a Tilt Sensor that I have on my door, but would be great if we could allow users to add a binary sensor (tilt or door) to track door status.

I use the below to create a custom cover.

```
cover:
  - platform: template
    covers:
      garage_door_left_c:
        device_class: garage
        friendly_name: "Garage: Left Door"
        value_template: "{{ is_state('binary_sensor.garage_left_tilt_door' , 'on') }}"
        unique_id: garage_door_left_id
        open_cover:
          service: cover.open_cover
          entity_id: cover.garage_left_door
        close_cover:
          service: cover.close_cover
          entity_id: cover.garage_left_door
        stop_cover:
          service: cover.stop_cover
          entity_id: cover.garage_left_door
        icon_template: >-
          {% if is_state('binary_sensor.garage_left_tilt_door' , 'on') %}
            mdi:garage-open
          {% else %}
            mdi:garage
          {% endif %}
```
