### ISSUE TITLE
Dry Contact Troubleshooting

### ISSUE THREAD

**Issue by roblandry** [ratgdo/esphome-ratgdo#137]
Just installed everything and wired according to the instructions "Example wiring for a Genie opener". 

![WIRING](https://github.com/ratgdo/esphome-ratgdo/assets/1853884/a6594a78-5010-4009-8f60-71b9486efb9a)

Currently i get the open and close sensors in esphome and home assistant, but the door state is wrong (never changes) and open/close control does not work.

![Screenshot 2023-12-09 140407](https://github.com/ratgdo/esphome-ratgdo/assets/1853884/5ead3020-7283-400f-b8a4-cecb21806648)

Esphome config:

```yaml
substitutions:
  id_prefix: ratgdov25i
  friendly_name: ratgdov2.5i
  uart_tx_pin: D1
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

web_server:

esphome:
  name: ${id_prefix}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: true
  project:
    name: ratgdo.esphome
    version: "2.5i"

esp8266:
  board: d1_mini_lite
  restore_from_flash: true

dashboard_import:
  package_import_url: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

# Sync time with Home Assistant.
time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server
  encryption:
    key: REDACTED

ota:

improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
  ap:

logger:
```
