### ISSUE TITLE
ratGDO ESP firmware update to 2023.12.1 fails with error: not enough space to store OTA file

### ISSUE THREAD

**Issue by davidcom2** [ratgdo/esphome-ratgdo#155]
This is my first time ever posting an issue on github. Apologies in advance if I don't report this issue correctly, or if this is the wrong place to report it. 

I'm trying to update my esphome ratgdo in Home Assistant. I'm getting the following message: 

`ERROR Error binary size: Error: ESP does not have enough space to store OTA file. Please try flashing a minimal firmware (remove everything except ota)`

Can anyone give advice on how to resolve this? I'm afraid I don't know how to do what is being suggested ("Please try flashing a minimal firmware (remove everything except ota)")

Note: The current version it's trying to update to is 2023.12.3, but I believe the issue started when trying to update to 2023.12.1.

Thanks!

**Comment by towerhand** [comment]
https://github.com/ratgdo/esphome-ratgdo/issues/136#issuecomment-1865903037

**Comment by edrikk** [comment]
Not sure how/if it applies to the esp version, but thought to share just in case.

https://github.com/ratgdo/homekit-ratgdo/pull/50

**Comment by davidcom2** [comment]
> [#136 (comment)](https://github.com/ratgdo/esphome-ratgdo/issues/136#issuecomment-1865903037)

Thanks. I followed those instructions and was able to complete the update. I don't know if that update process will have to be done every time the ratgdo has an update in ESPHome. Hopefully not because it's somewhat involved just to update. 

Thanks again!

**Comment by robby-dermody** [comment]
So given the comment at https://github.com/ratgdo/homekit-ratgdo/pull/50 that the ratgdo has 4MB of flash (thanks @edrikk ), is that actually the case? And if so, why does the ESPhome config list the board as a `d1_mini_lite`, which has 1MB flash capacity from what I can tell? Maybe this is as simple as changing the `board:` config to get the access to that extra memory?

**Comment by kpfleming** [comment]
The 2.5i board I received today has an ESP-12F which does have 4MB of flash, so I've configured ESPHome for `d1_mini` instead of `d1_mini_lite` and it's working fine. I suspect given the backorder situation there may be a variety of 2.5i boards out there with different ESP modules on them and the 'standard' config is designed to work on all of them.

**Comment by bdraco** [comment]
AFAICT all the 2.5is are ESP-12F so we can change https://github.com/ratgdo/esphome-ratgdo/blob/587ff4c7c5c40d438469448319a665823c02840f/static/v25iboard.yaml#L25 to `d1_mini` but need @PaulWieland to confirm before making that change

**Comment by PaulWieland** [comment]
@bdraco Confirmed.

**Comment by bdraco** [comment]
New images will be up in 10-15 minutes

**Comment by bdraco** [comment]
https://github.com/ratgdo/esphome-ratgdo/actions/runs/7311723573

**Comment by shred86** [comment]
I'm having this same issue on a ratgdo 2.0 board (esp8266 d1 mini lite). Is there a work around for this version? All of the comments on the various issues are in reference to the v2.5i board.

**Comment by bdraco** [comment]
Replace the esp with the non lite version.

**Comment by shred86** [comment]
Sorry, dumb question but just to clarify - are you saying buy a new physical esp device because there's no work around for the v2.0 esp8266 board? Or to change the config file to use the d1_mini instead of d1_mini_lite?

**Comment by shred86** [comment]
I'm not sure. I ordered it from Paul Wieland's website when the v2.0 boards were the latest. On the ESPHome ratgdo web install page, it looks identical to what's pictured as the ESP8266 (left most). Of course I can't find the email receipt since I was hoping maybe that identifies it. Otherwise, I'll just have to pull it down from the garage door opener and check I suppose.

**Comment by shred86** [comment]
That being said, I'm pretty sure it's a D1 Mini Lite since I've been using v2board_esp8266_d1_mini_lite.yaml. If that's the case, then the only workaround I can think of that seems to have worked is just completely stripping down the configuration to minimize the file size. I was able to get the latest version of ESPHome firmware using the yaml example below. I removed several things that I didn't think were necessary, to include the web server. I suppose the only downside of this is if there's any changes upstream, then I'll have to manually make the updates (unless they're changes in the base.yaml file which is still being pulled).

````yaml
substitutions:
  id_prefix: ratgdov2
  name: ratgdov2-xxxxxx
  friendly_name: ratgdov2 xxxxxx
  uart_tx_pin: D4
  uart_rx_pin: D2
  input_obst_pin: D7
  status_door_pin: D0
  status_obstruction_pin: D8
  dry_contact_open_pin: D5
  dry_contact_close_pin: D6
  dry_contact_light_pin: D3

esphome:
  name: ${name}
  friendly_name: ${friendly_name}
  name_add_mac_suffix: false
  project:
    name: ratgdo.esphome
    version: "2.0"

esp8266:
  board: d1_mini_lite
  restore_from_flash: true

packages:
  remote_package:
    url: https://github.com/ratgdo/esphome-ratgdo
    files: [base.yaml]
    refresh: 1s

time:
  - platform: homeassistant
    id: homeassistant_time

api:
  id: api_server
  encryption:
    key: redacted

ota:

improv_serial:

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

logger:
````

**Comment by rlowens** [comment]
Note that you can still do the 2-step OTA update: install a minimal .yaml with just the device name and OTA, then install the full .yaml.

**Comment by rlowens** [comment]
> That being said, I'm pretty sure it's a D1 Mini Lite since I've been using v2board_esp8266_d1_mini_lite.yaml.

Doesn't mean that's what the device actually has, just that it worked with that setting.

To test the real flash size, you can download [esptool](https://github.com/espressif/esptool/releases/latest) and run:

`esptool.exe flash_id`

Example results on my NodeMCU dev board (I don't have any d1 mini style boards):

> esptool.exe flash_id
> esptool.py v4.7.0
> Found 2 serial ports
> Serial port COM7
> Connecting....
> Detecting chip type... Unsupported detection protocol, switching and trying again...
> Connecting....
> Detecting chip type... ESP8266
> Chip is ESP8266EX
> Features: WiFi
> Crystal is 26MHz
> MAC: dc:4f:22:12:15:81
> Uploading stub...
> Running stub...
> Stub running...
> Manufacturer: 20
> Device: 4016
> Detected flash size: 4MB
> Hard resetting via RTS pin...
> 

Note: the Windows Defender detection of virus AndroidOS/ZkarletFlash is a false-positive, but instead of going thru the hassle of allowing it in Windows Defender and then re-trying the download, you can just get the v4.6.2 older release that seems to scan fine for me. https://github.com/espressif/esptool/releases/tag/v4.6.2

I reported this problem at https://github.com/espressif/esptool/issues/944

**Comment by bdraco** [comment]
If it turns out to not be a lite, we can add the non-lite version to the site

**Comment by shred86** [comment]
Here's the output of the debug with that sensor added:

````
[02:58:36][D][debug:076]: ESPHome version 2023.12.5
[02:58:36][D][debug:080]: Free Heap Size: 18616 bytes
[02:58:36][D][debug:108]: Flash Chip: Size=1024kB Speed=40MHz Mode=DOUT
[02:58:36][D][debug:323]: Chip ID: 0x00C84EAE
[02:58:36][D][debug:324]: SDK Version: 2.2.2-dev(38a443e)
[02:58:36][D][debug:325]: Core Version: 3.0.2
[02:58:36][D][debug:326]: Boot Version=7 Mode=1
[02:58:36][D][debug:327]: CPU Frequency: 80
[02:58:36][D][debug:328]: Flash Chip ID=0x0016405E
[02:58:36][D][debug:329]: Reset Reason: Software/System restart
[02:58:36][D][debug:330]: Reset Info: Software/System restart
````

**Comment by bdraco** [comment]
I added a d1 mini board to the site https://ratgdo.github.io/esphome-ratgdo/

**Comment by rlowens** [comment]
> Edit: The "Flash Real Size" is showing 4194304.0.

Great! So it really isn't a "lite"

**Comment by amaisano** [comment]
Sorry, what's the solution to this? I already tried the new firmware. The next ESPHome update this week causes the same issue again...

**Comment by bdraco** [comment]
flash once from the website and than it will be updatable from the dashboard

**Comment by PPatla** [comment]
If you have encryption enabled you can just rem it out, do the update then put it back.

I started with the 2.5i firmware, then REMd it out to go to the beta, then changed over the to main and all my ESPHOME updates work no problem

substitutions:
  name: ratgdov25i
  friendly_name: ratgdo single
packages:
#  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
# ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@sec_plus_v1
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: 3RqH5ILTG5fWhaetXSiLg74P0u28MhIDsf37N8fVg+o=


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

**Comment by shaunburdick** [comment]
I was able to do it by flashing a base image first via OTA, then my normal.

If it helps, here is the process:

1. Comment out your normal config, add just ESPHome and OTA:
```yaml
substitutions:
  name: ratgdov25i
  friendly_name: Ratgdo Garage Door

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
esp8266:
  board: d1_mini
ota:
```
2. Perform the OTA Build and Install
3. Put your normal config back
4. Perform the OTA Build and Install

I kept the small version as a comment in case I need it again:
```yaml
substitutions:
  name: ratgdov25i
  friendly_name: Ratgdo Garage Door

# FOR USE
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main

esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}

api:
  encryption:
    key: !secret api_encryption_key

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

# # FOR UPDATE
# esphome:
#   name: ${name}
#   name_add_mac_suffix: false
#   friendly_name: ${friendly_name}
# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password
# esp8266:
#   board: d1_mini
# ota:
```
