### ISSUE TITLE
Lock remotes switch in HA unavailable

### ISSUE THREAD

**Issue by mattfox27** [ratgdo/esphome-ratgdo#163]
I have this lock remores switch that is unavailable![Screenshot_20240101_000717_Home Assistant.jpg](https://github.com/ratgdo/esphome-ratgdo/assets/6801877/748ef900-d8fc-49fe-b3bb-1b3928b07ba1)

**Comment by mulcmu** [comment]
#132 changed this from a switch to lock component.  Looks like your setup didn't pull in changes from the base.yaml.
```
lock:
  - platform: ratgdo
    id: ${id_prefix}_lock_remotes
    ratgdo_id: ${id_prefix}
    name: "Lock remotes"
```
