### ISSUE TITLE
Feature Request: Dry Contact Virtual Limit Switch

### ISSUE THREAD

**Issue by Seechay** [ratgdo/esphome-ratgdo#205]
Hello! I would like to request the ability to supply Home Assistant and/or MQTT binary sensors to use for limit switches instead of being wired to the pins. This could be used to replace the open/close triggers to any arbitrary sensor(s). In my use case I have two zigbee contact switches being used to monitor the garage door state, as wiring would be overly complex. There are also wireless tilt sensors that could be used, which would be able to provide binary triggers.

**Comment by mariusmuja** [comment]
Give this branch a try: https://github.com/ratgdo/esphome-ratgdo/tree/dry_contact_with_sensors

Add the home assistant sensors to the `ratgdo` component like this:

```
ratgdo:
  id: ${id_prefix}
...
  protocol: drycontact
  door_open: ${id_prefix}_door_open
  door_closed: ${id_prefix}_door_closed
...
  ```

where the sensors are some homeassistant binary sensors (for example I've tested with some zigbee hall sensors):
```
  - platform: homeassistant
    name: "Door Open Sensor"
    id: ${id_prefix}_door_open
    entity_id: binary_sensor.door_sensor_open   # entity_id from home assistant
    filters: 
      - invert
 
  - platform: homeassistant
    name: "Door Closed Sensor"
    id: ${id_prefix}_door_closed
    entity_id: binary_sensor.door_sensor_closed     # entity_id from home assistant
    filters: 
      - invert
```
