### ISSUE TITLE
Reverse functionality [Enhancement]

### ISSUE THREAD

**Issue by mvannas** [ratgdo/esphome-ratgdo#217]
I have two door garage with sideways opening doors. 

Due to space constraints one door opener is installed in reverse. This means it shows OPEN when close and CLOSED when open. There is no way to make the Liftmaster operate in reverse, but I was wondering if a reverse functionality could be implemented in ratgdo, at least so that open/close status and buttons would show correctly to ESPHome/Home assistant etc.?

**Comment by rlowens** [comment]
You can do this by editing your device .yaml file. Here's how I cam up with my suggestion:

1. Get the ratgdo working (backwards in your case) and adopted in ESPHome Dashboard so you have a device .yaml to edit.
2. Digging around here on github we find the source file we need to modify https://github.com/ratgdo/esphome-ratgdo/blob/main/base.yaml Here's what the current cover looks like:
```
cover:
  - platform: ratgdo
    id: ${id_prefix}_garage_door
    device_class: garage
    name: "Door"
    ratgdo_id: ${id_prefix}
    on_closed:
      - switch.turn_off: ${id_prefix}_status_door
    on_open:
      - switch.turn_on: ${id_prefix}_status_door

```
3. With this knowledge, you can then add your own modifications to the end of your device .yaml to change that cover how you want.. I suggest we change that original cover to be internal to ESPHome (so it won't be reported to Home Assistant) and create another template cover that reverses everything for us.

```
#custom modifications using https://esphome.io/guides/configuration-types.html#extend
cover:
  - id: !extend ${id_prefix}_garage_door
    internal: true
    name: "Internal Door"
#ref https://esphome.io/components/cover/template.html
  - platform: template
    id: ${id_prefix}_exposed_door
    name: Door
    device_class: garage
    has_position: false
    open_action:
      - cover.close: ${id_prefix}_garage_door
    close_action:
      - cover.open: ${id_prefix}_garage_door
    stop_action:
      - cover.stop: ${id_prefix}_garage_door
    toggle_action:
      - cover.toggle: ${id_prefix}_garage_door
    optimistic: true
```

I think that would do it? Note that once PR https://github.com/ratgdo/esphome-ratgdo/pull/195 is merged this can be re-written and enable position-control instead of just open/closed only.
