### ISSUE TITLE
Garage Door - RATGDO - Security 1.0 - No Stop Cover Or Percentage Open + Logs Flooding

### ISSUE THREAD

**Issue by Steven4x4** [ratgdo/esphome-ratgdo#223]
I originally posted this in the wrong github area. Hopefully this is the right one.

### The problem

I'm new to ESP Home. RATGDO is my first ESP Home device.
I'm not entirely sure what ESP Platform the v2.53i  is.

When I go to the ESP Home Devices Webpage Directly...
With the RATDGO v2.53i board with the Security 1.0 firmware it is flooding the logs every other second with:
14:46:32 | [D] | [ratgdo:210] | Lock state=UNLOCKED
14:46:33 | [D] | [ratgdo:204] | Light state=OFF
14:46:33 | [D] | [ratgdo:210] | Lock state=UNLOCKED
14:46:35 | [D] | [ratgdo:204] | Light state=OFF
14:46:35 | [D] | [ratgdo:210] | Lock state=UNLOCKED
14:46:36 | [D] | [ratgdo:204] | Light state=OFF
Video - https://www.youtube.com/watch?v=F8vxAVPcjjo
In the video Security 1.0 on the left, security 2.0 on the right.

For reference on the Security 2.0 firmware, it only does this every 5 minutes. (Which is about what I would expect.

Secondly, inside of home assistant, on the integrations > esp home > garage door device.
When you try to use the feature where you can open to a specific percentage. It does no work on the 1.0 firmware, but does work on the 2.0 firmware. I reach out to RATDGO directly, and he directed me to post here.
Additional, Open Cover works, but Stop Cover does not.

### Which version of ESPHome has the issue?

2023.12.9

### What type of installation are you using?

Home Assistant Add-on

### Which version of Home Assistant has the issue?

2024.1.6

### What platform are you using?

ESP32

### Board

RATGDO v2.53i

### Example YAML snippet

```yaml
ESP HOME YAML:
substitutions:
  name: ratgdov25i-ca08b2
  friendly_name: Garage Door 1
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: <REDACTED>


wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
