### ISSUE TITLE
RATGDO not working with a Liftmaster 8355

### ISSUE THREAD

**Issue by jrfernandes** [ratgdo/esphome-ratgdo#243]
Hello all.

I got a RATGDO v2.5 board and flashed it with ESPHome using the [official web flash tool](https://ratgdo.github.io/esphome-ratgdo/). I selected "Security + 2.0" + "ratgdo v2.5x".

Then, connected to my Liftmaster 8355 (yellow learn button) according to the diagram on the website.

None of the controls work, and when opening ESPHome webpage, I see a lot of these errors:
```
19:37:37 | [W] | [ratgdo_secplus1:262] | [602273] Discard incomplete packet: [39 ...]
19:37:37 | [W] | [ratgdo_secplus1:262] | [602532] Discard incomplete packet: [38 ...]
19:37:37 | [W] | [ratgdo_secplus1:262] | [602792] Discard incomplete packet: [3A ...]
19:37:37 | [W] | [ratgdo_secplus1:262] | [603050] Discard incomplete packet: [39 ...]
 ...
```

Opening/closing the door, or turning on the light does not work. The statuses are not updating either, with the exception of the obstruction status, which does work.

What am I missing?

My ESPHome yaml:
```yaml
substitutions:
  name: "garage-door"
  friendly_name: garage-door
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard_secplusv1.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: !secret api_key
wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```

Pictures of the GDO:
![IMG_7495 Large](https://github.com/ratgdo/esphome-ratgdo/assets/638906/df87c4d6-a070-49f0-b952-1c82962a7546)
![IMG_7496 Large](https://github.com/ratgdo/esphome-ratgdo/assets/638906/67d8062b-bc6f-446c-8f46-e4cf5d6c4a52)
