### ISSUE TITLE
Disable API reboot timeout.

### ISSUE THREAD

**Issue by hjdhjd** [ratgdo/esphome-ratgdo#262]
Would be great if we could have the YAML updated such that the Ratgdo didn't auto reboot every 15 minutes if you don't connect to the native API. Those of us using the web API rather than the native API have to workaround this constraint currently.

Disabling the auto reboot is straightforward in the YAML.

```
api:
  id: api_server
  reboot_timeout: 0s
```

@PaulWieland Any chance you can add this to the YAML? It'd be incredibly helpful. Thanks!

**Comment by PaulWieland** [comment]
No, thats not in the plan. The reboot is quite intentional to help with unstable networks. 

From the [ESP Home FAQ](https://esphome.io/guides/faq.html#:~:text=ESPHome%20reboots%20on%20purpose%20when,or%20mqtt%20connection%20is%20lost.):
> ESPHome reboots on purpose when something is not going right, e.g. [wifi connection cannot be made](https://esphome.io/components/wifi) or [api connection is lost](https://esphome.io/components/api) or [mqtt connection is lost](https://esphome.io/components/mqtt).

You can simply clone the project and update yaml to suit your needs. You can also initiate a connection to the API socket just like Home Assistant does and that will prevent it from rebooting.

**Comment by hjdhjd** [comment]
That's already what I do. I just find it inelegant. 😄

Appreciate the clarity on your plans. Thanks and keep up the great work!

**Comment by rlowens** [comment]
You don't even need to clone the project, just put that in your own device .yaml in the api: section that already exists.

```
substitutions:
  name: ratgdov2-11999c
  friendly_name: ratgdo
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v2board_esp8266_d1_mini.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: iWx8Hghy47j8zEC4IVqJousY+SZI+U1S0X1VWLp3Zz8=
  reboot_timeout: 0s

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password
```
