### ISSUE TITLE
OTA Updates Fail with Non-Standard OTA Port

### ISSUE THREAD

**Issue by dolai1** [ratgdo/esphome-ratgdo#297]
Hello.

It seems that, after one of the June updates to ESPHome (I am now on 2024.6.4), I can no longer OTA update my ratgdos on non-standard ports.

ESPHome tries to connect to 8266 for the upload, even though the config files have other ports specified (8270, 8271, 8272, etc.):
```
ota:
 - platform: esphome
   password: !secret gdo_ota_pwd
   port: 8272
```

I can still access my web interface of each of the devices and confirm that they are still listening on the non-standard ports for OTA connections. I can also still update via the web interface.

I think that this must have something to do with the fact that the required OTA section format changed in 2024.6 (the "platform: esphome" is new, IIRC).

I am posting the issue here rather than on the ESPHome page because all of my other ESPHome devices with nonstandard ports update OTA appropriately; there seems to be something from the ratgdo side that is causing this to fail. Moreover, it worked properly before the "platform: esphome" changeover in June.

Thank you.

**Comment by DAVe3283** [comment]
I believe that you are ending up with 2 OTA components, since there is one built into the RATGDO firmware.

You have to extend/modify the existing OTA component to change the port. Try this:

```yaml
ota:
  - id: !extend ratgdo_ota
    password: !secret gdo_ota_pwd
    port: 8272
```
