### ISSUE TITLE
Open/Closed entity in Homeassistant 

### ISSUE THREAD

**Issue by ba05** [ratgdo/esphome-ratgdo#353]
Is it possible to add an open/closed entity in home assistant? If I click on the door button it says "Closed" or "Open" but I can't access this through an entity.

**Comment by doctorkb** [comment]
The `cover` entity should have that as the state...

**Comment by ba05** [comment]
```cover``` has it as a state, but this cannot directly be added to an entity card without creating a binary sensor using the close/open value.

**Comment by doctorkb** [comment]
You could use a template card. Or, if you're that set on a binary sensor, just set up a helper.

**Comment by tmason818** [comment]
I use this for a  simple Open/Close toggle:
https://www.home-assistant.io/integrations/cover.template/

This is the code I added to my configuration.yaml.



```
#Virtual Garage Door control entity for "toggle" up/down Toggle control
cover:
  - platform: template
    covers:
      garage_door:
        device_class: garage
        friendly_name: "Virtual Garage Door Control"
        value_template: "{{ states('cover.garage_door_ratgdo_21719_door') }}"
        open_cover:
          action: cover.open_cover
          entity_id: cover.garage_door_ratgdo_21719_door
        close_cover:
          action: cover.close_cover
          entity_id: cover.garage_door_ratgdo_21719_door
``` 

You'll end up with a new entity you can add to cards:

![image](https://github.com/user-attachments/assets/1c4e6ef3-e135-4fd7-b839-b87555a20b8f)
