### ISSUE TITLE
Not a valid value error when attempting to compile on windows.

### ISSUE THREAD

**Issue by tanderson1992** [ratgdo/esphome-ratgdo#388]
Using ratgdo v2.5 on a Security 2.0 opener. When attempting to update on Windows with the command `esphome -q update-all .` fails with the following error:
```
Failed config

packages: [source grandmomgarage.yaml:5]

  not a valid value.
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
```

This is the yaml file's contents:
```
substitutions:
  name: grandmomgarage
  friendly_name: Grandmom Garage
packages:
  ratgdo.esphome: github://ratgdo/esphome-ratgdo/v25iboard.yaml@main
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
api:
  encryption:
    key: [redacted]


wifi:
  ssid: "[redacted]"
  password: "redacted"
  fast_connect: true
```
The identical yaml file works through ESPHome Builder in Home Assistant on a Raspberry Pi 5. Do changes need to be made to the yaml for it to compile on Windows? I usually compile ESPHome on my Windows machine because it's a lot faster, compiling new firmware in less than 20 seconds compared to 5+ minutes per device on the RPi.

**Comment by tanderson1992** [comment]
And just to be clear, I have other devices with the github line that work fine. For example:
```
substitutions:
  device_name: "chili"
  name: "${device_name}"
  upper_devicename: Chili
  friendly_name: Chili
  relay_restore_mode: RESTORE_DEFAULT_OFF
packages:
  Athom_Technology.Smart_Plug_V2: github://athom-tech/athom-configs/athom-smart-plug-v2.yaml
esphome:
  name: ${name}
  name_add_mac_suffix: false
  friendly_name: ${friendly_name}
<<: !include includes/plug-common.yaml
```
