### ISSUE TITLE
STOPPED vs open

### ISSUE THREAD

**Issue by tfcarlin** [ratgdo/esphome-ratgdo#45]
Hi,

I'm attempting to control a door with a single button. I would like the button to act just like a "normal" button. In the US I'm pretty sure the state machine is:

1. If closed then open.
2. If open then close. 
3. If opening then stop.
4. If closing then open.
5. If stopped then close.

If the door is closed, I press the normal wall control button the door will start to open, and with another press the door will stop.

Using Home Assistant (web interface)->Developer tools->TEMPLATE this code:

```
{{ states('cover.ratgdov2_big_door') }}
```
returns:

```The door state is open.```

but it should return:

```The door state is stopped.```

In the log the Status shows STOPPED but the state is reported as OPEN (in HA and the ESPHome UI) 

```
07:22:26 | [D] | [cover:170] | 'Door' - Publishing:
-- | -- | -- | --
07:22:26 | [D] | [cover:173] | Position: 38%
07:22:26 | [D] | [cover:186] | Current Operation: CLOSING
07:22:27 | [D] | [ratgdo:595] | Cancelling position callbacks
07:22:27 | [D] | [ratgdo:188] | Status: door=STOPPED light=ON lock=UNLOCKED
07:22:27 | [D] | [cover:170] | 'Door' - Publishing:
07:22:27 | [D] | [cover:173] | Position: 38%
07:22:27 | [D] | [cover:186] | Current Operation: IDLE
07:22:29 | [D] | [esp8266.preferences:238] | Saving preferences to flash...
07:23:00 | [D] | [button:010] | 'Query status' Pressed.
07:23:00 | [D] | [number:012] | 'Rolling code counter': Sending state 435.000000
07:23:00 | [D] | [ratgdo:188] | Status: door=STOPPED light=ON lock=UNLOCKED
```
![image](https://github.com/ESPHome-RATGDO/esphome-ratgdo/assets/115871/48bab0a4-2f3e-4827-a6c2-111303307024)

Thanks for the help!

**Comment by mariusmuja** [comment]
The status you see in the log is internal to ratgdo. In the esphome web interface it's always either "OPEN" or "CLOSED":

https://github.com/esphome/esphome/blob/dev/esphome/components/web_server/web_server.cpp#L732

In home assistant, when it's open, you need to look at the `current_position` attribute:
```
{{ state_attr('cover.ratgdov2_big_door', 'current_position') }}
```

**Comment by tfcarlin** [comment]
OK, thanks.

**Comment by tfcarlin** [comment]
In case anyone else is interested in a single button control that acts like a hardwired button here is how I implemented it.

automations.yaml

```
- id: '1694522094244'
  alias: BigDoor Normal Actions
  trigger:
  - platform: state
    entity_id: binary_sensor.garagedoors_bigbutton
    to: 'on'
  action:
  - service: script.garage_door_control
    data: {}
```


scripts.yaml

```
garage_door_control:
  alias: Garage Door Control Script
  sequence:
  - choose:
    - conditions:
      - condition: or
        conditions:
        - condition: template
          value_template: '{{ states(''cover.ratgdov2_big_door'') == ''closed'' }}'
        - condition: template
          value_template: '{{ states(''cover.ratgdov2_big_door'') == ''closing'' }}'
      sequence:
      - service: cover.open_cover
        entity_id: cover.ratgdov2_big_door
    - conditions:
      - condition: template
        value_template: '{{ states(''cover.ratgdov2_big_door'') == ''open'' }}'
      - condition: template
        value_template: '{{ state_attr(''cover.ratgdov2_big_door'', ''current_position'')
          == 100 }}'
      sequence:
      - service: cover.close_cover
        entity_id: cover.ratgdov2_big_door
    - conditions:
      - condition: template
        value_template: '{{ states(''cover.ratgdov2_big_door'') == ''opening'' }}'
      sequence:
      - service: cover.stop_cover
        entity_id: cover.ratgdov2_big_door
    - conditions:
      - condition: template
        value_template: '{{ states(''cover.ratgdov2_big_door'') == ''open'' }}'
      - condition: template
        value_template: '{{ state_attr(''cover.ratgdov2_big_door'', ''current_position'')
          < 100 }}'
      sequence:
      - service: cover.close_cover
        entity_id: cover.ratgdov2_big_door
```
