### ISSUE TITLE
Home Assistant Card Code? 

### ISSUE THREAD

**Issue by keithnet** [ratgdo/esphome-ratgdo#59]
Sorry, I've looked around a bunch and cant find the code to do a card in home assistant as shown in the Readme (with opening percentages). Can someone point me in the right direction?

**Comment by mariusmuja** [comment]
You could add the garage door cover entity to a number of cards, for example you could add a Button card with the following content:
```yaml
show_name: true
show_icon: true
type: button
entity: cover.garage_door
icon: mdi:garage
name: Garage door
```

![image](https://github.com/ratgdo/esphome-ratgdo/assets/695669/5a870dfb-a241-46f2-9daa-768cec2f94bf)

and clicking on it would open the cover dialog as shown in the Readme. The entity name would likely be different for you.
